
// What is MongoDB, and how is it different from traditional relational databases?
// ans: MongoDB is a NoSQL database that stores data in flexible, JSON-like documents. It is different from traditional relational databases in that it does not require a fixed schema, uses a flexible data model, and is designed to scale horizontally across multiple servers.


// Explain the concept of NoSQL. How does MongoDB fit into the NoSQL ecosystem?
// ans : NoSQL stands for "Not Only SQL" and refers to databases that use non-tabular data models and do not require a fixed schema. MongoDB fits into the NoSQL ecosystem by using a flexible document data model that allows for easy scalability and high performance.


// What is a document in MongoDB, and how is it structured?
// ans: A document in MongoDB is a JSON-like data structure that stores data in key-value pairs. It is similar to a row in a relational database table but does not require a fixed schema. Documents can contain nested fields, arrays, and other complex data types.

// What is a collection in MongoDB? How does it compare to a table in SQL databases?
// ans: A collection in MongoDB is a group of documents stored in the same database. It is similar to a table in SQL databases but does not require a fixed schema. Collections can contain documents with different fields and data types, making them more flexible than traditional tables.


// What is the role of _id in MongoDB documents?
// ans: The _id field in MongoDB documents is a unique identifier for each document in a collection. It is automatically generated by MongoDB and ensures that each document is uniquely identified within the collection.

// Explain the BSON format. Why does MongoDB use BSON?
// ans: BSON stands for "Binary JSON" and is a binary-encoded serialization of JSON-like documents. MongoDB uses BSON to store and retrieve data efficiently, as it provides a more compact representation of data and supports additional data types and features not available in JSON.

// How do you insert a document into a MongoDB collection?
// ans: You can insert a document into a MongoDB collection using the insertOne or insertMany methods. For example, to insert a single document, you can use the following syntax:
// db.collection.insertOne({ key: value });
// To insert multiple documents, you can use the insertMany method with an array of documents:
// db.collection.insertMany([{ key: value }, { key: value }]);


// What is a replica set in MongoDB? Why is it used?
// ans: A replica set in MongoDB is a group of MongoDB servers that maintain the same data set. It is used to provide high availability and data redundancy by replicating data across multiple servers. Replica sets ensure that data is always available and can be recovered in case of server failures.

// Explain the difference between a primary and a secondary node in MongoDB replication.
// ans: In MongoDB replication, a primary node is the main server that receives all write operations and is responsible for replicating data to secondary nodes. Secondary nodes are read-only copies of the primary data and are used for read operations. If the primary node fails, a secondary node can be elected as the new primary.

// How does MongoDB ensure data consistency?
// ans: MongoDB ensures data consistency through replica sets and write concern settings. Replica sets replicate data across multiple servers to provide redundancy and high availability. Write concern settings allow you to specify the level of acknowledgment required from servers to ensure that data is written consistently.

// Intermediate Questions
// What is sharding in MongoDB, and why is it used?
// ans: Sharding in MongoDB is the process of distributing data across multiple servers to improve performance and scalability. It is used to horizontally scale databases by partitioning data into smaller chunks called shards and distributing them across multiple servers.

// How does MongoDB handle indexing? What are some common types of indexes?
// ans: MongoDB uses indexes to improve query performance by storing a sorted representation of data. Some common types of indexes in MongoDB include single-field indexes, compound indexes, multikey indexes, and text indexes.

// How would you perform a query to fetch specific fields from a document?
// ans: You can use the projection parameter in a find query to fetch specific fields from a document. For example, to fetch only the name and age fields from a document, you can use the following syntax:
// db.collection.find({}, { name: 1, age: 1 });

// What is an aggregation pipeline? Give an example of when to use it.
// ans: An aggregation pipeline in MongoDB is a framework for data aggregation operations. It allows you to process data from a collection in multiple stages, such as filtering, grouping, and sorting. You can use an aggregation pipeline to perform complex data transformations and calculations on large datasets.

// add lookup, unwind, project, sort, limit, skip, etc.
// syntax : db.collection.aggregate([ { $match: { <query> } }, { $group: { _id: <expression>, <field1>: { <accumulator1> }, ... } }, { $sort: { <field1>: <order>, ... } }, { $project: { <field1>: <1|0>, ... } }, { $limit: <num> }, { $skip: <num> } ]);


// How does MongoDB handle concurrency and transactions?
// ans: MongoDB uses a locking mechanism to handle concurrency and ensure data consistency. It supports multi-document transactions in replica sets and sharded clusters, allowing you to perform multiple read and write operations atomically.

// Explain the use of updateOne vs. updateMany in MongoDB and difference.
// ans: The updateOne method in MongoDB updates a single document that matches a specified filter, while the updateMany method updates multiple documents that match a specified filter. You can use updateOne to update a specific document, and updateMany to update multiple documents at once.


// What is the findOneAndUpdate method, and when would you use it?
// ans: The findOneAndUpdate method in MongoDB finds a single document that matches a specified filter, updates it, and returns the updated document. You can use it to atomically update a document and retrieve the updated result in a single operation.

// How does MongoDB's MapReduce functionality work?
// ans: MongoDB's MapReduce functionality allows you to process and analyze large datasets using map and reduce functions. The map function processes each document and emits key-value pairs, which are then grouped and reduced by the reduce function to produce the final result.


// Explain the purpose of capped collections in MongoDB.
// ans: Capped collections in MongoDB are fixed-size collections that maintain insertion order and automatically remove old documents when the collection reaches its size limit. They are used for high-throughput operations like logging and event tracking.


// How does MongoDB's GridFS work, and when would you use it?
// ans: MongoDB's GridFS is a specification for storing and retrieving large files in MongoDB. It divides files into smaller chunks and stores them as separate documents in a collection. You can use GridFS to store files that exceed the 16MB document size limit in MongoDB.


// Advanced Questions
// How do you design a schema in MongoDB for a highly scalable application?
// What are some performance tuning techniques in MongoDB?
// How does MongoDB handle schema changes in collections?
// Explain the purpose and use of compound indexes in MongoDB.
// How would you troubleshoot a slow-running query in MongoDB?
// How does MongoDB handle durability, especially in high-availability systems?
// What is the purpose of mongodump and mongorestore?
// Explain how to use change streams to monitor data changes in MongoDB.
// How would you set up a MongoDB sharded cluster?
// Explain the role and configuration of journaling in MongoDB.